# Generated by Django 4.0.4 on 2022-06-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_profile_bio_profile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
    ]
